### ISSUE TITLE
muc-loader doesn't compile on Ubuntu 18.04: "conflicting CPU architectures" 

### ISSUE THREAD

**Issue by reinvantveer** [MotorolaMobilityLLC/muc-loader#8]
Assuming compilation of muc-loader is mandatory for openocd firmware flashing (following https://developer.motorola.com/documentation/flashing-firmware#flashing-muc-bootloader), the building of muc-loader fails on Ubuntu 18.04:
```
$ ./configure hdk/developer # following https://developer.motorola.com/documentation/build-source#compile-bootloader
$ make
...

/usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/bin/ld: error: /usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/lib/rdimon-crt0.o: Conflicting CPU architectures 13/1
/usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/bin/ld: failed to merge target specific data of file /usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/lib/rdimon-crt0.o
/usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/bin/ld: error: out/boot_hdk.elf uses VFP register arguments, /usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/lib/libc.a(lib_a-atexit.o) does not
```
Full output in attached file
[make_output.txt](https://github.com/MotorolaMobilityLLC/muc-loader/files/2569257/make_output.txt)

Help much appreciated

**Comment by jnasti1** [comment]
Probably a little late, but your workaround for this Ubuntu 18.04 bug is referenced here by upgrading newlib to a newer version.

https://bugs.launchpad.net/ubuntu/+source/newlib/+bug/1767223/comments/10

**Comment by reinvantveer** [comment]
@jnasti1 your help is greatly appreciated, thanks! I'll give it a try.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
